"""Callbacks DAT of the WebRTC DAT.

The signatures are the ones generated by TouchDesigner 2025.32050: do not change
them. Only negotiation lives here; the dialogue with the backend is in
webrtc_signaling.py, on the Callbacks DAT of the WebSocket DAT.

The full round trip:

    1. the panel opens            -> the backend sends `peer.joined`
    2. webrtc_signaling opens the connection and attaches the Video Stream Out
    3. attaching the video should raise onNegotiationNeeded -> createOffer
    4. the ready offer arrives in onOffer -> setLocalDescription, then is sent
    5. the panel answers          -> setRemoteDescription('answer')
    6. addresses are exchanged    onIceCandidate <-> addIceCandidate
    7. onConnectionStateChange reports 'connected': the video flows
"""

import json

#: The WebSocket DAT that talks to the backend. The WebRTC DAT callbacks produce
#: the messages but do not know where to send them.
SIGNAL_DAT = 'websocket1'


def _send(message: dict) -> None:
    dat = op(SIGNAL_DAT)
    if dat is None:
        debug(f'webrtc: {SIGNAL_DAT} non trovato, messaggio perso')
        return
    dat.sendText(json.dumps(message))


def onOffer(webrtcDAT: webrtcDAT, connectionId: str, localSdp: str):
    # Order matters: adopt the local description first, then send it. The other
    # way round, a very fast answer from the panel could arrive with nothing
    # here to apply it to.
    webrtcDAT.setLocalDescription(connectionId, 'offer', localSdp, stereo=False)
    _send({'type': 'offer', 'sdp': localSdp})
    debug('webrtc: offerta spedita al pannello')
    return


def onAnswer(webrtcDAT: webrtcDAT, connectionId: str, localSdp: str):
    # Should never fire: TouchDesigner is the offering side, being the one with
    # the video. Implemented anyway in case the panel ever offers something.
    webrtcDAT.setLocalDescription(connectionId, 'answer', localSdp, stereo=False)
    _send({'type': 'answer', 'sdp': localSdp})
    return


def onNegotiationNeeded(webrtcDAT: webrtcDAT, connectionId: str):
    """In theory fires when the Video Stream Out attaches its track.

    In this build it does not: attaching the track from the TOP parameter does
    not raise it, so the offer is requested explicitly by
    webrtc_signaling.create_offer() a couple of frames later. The log line stays
    as a marker: if it ever appears, the build has changed behaviour and the
    manual path can go.
    """
    debug(f'webrtc: onNegotiationNeeded ha finalmente scattato ({connectionId[:8]}...)')
    return


def onIceCandidate(webrtcDAT: webrtcDAT, connectionId: str, candidate: str,
                   lineIndex: int, sdpMid: str):
    _send({'type': 'candidate', 'candidate': candidate,
           'index': lineIndex, 'mid': sdpMid})
    return


def onIceCandidateError(webrtcDAT: webrtcDAT, connectionId: str, errorText: str):
    # With two peers on the same machine some candidates fail and that is
    # normal: others suffice. Just note it.
    debug(f'webrtc: candidato ICE fallito ({errorText})')
    return


def onTrack(webrtcDAT: webrtcDAT, connectionId: str, trackId: str, type: str):
    return


def onRemoveTrack(webrtcDAT: webrtcDAT, connectionId: str, trackId: str, type: str):
    return


def onDataChannel(webrtcDAT: webrtcDAT, connectionId: str, channelName: str):
    return


def onDataChannelOpen(webrtcDAT: webrtcDAT, connectionId: str, channelName: str):
    return


def onDataChannelClose(webrtcDAT: webrtcDAT, connectionId: str, channelName: str):
    return


def onData(webrtcDAT: webrtcDAT, connectionId: str, channelName: str, data: str):
    return


def onConnectionStateChange(webrtcDAT: webrtcDAT, connectionId: str, newState: str):
    # The line to watch when "nothing shows": it says whether the connection
    # completed, or where it stopped.
    debug(f'webrtc: connessione {newState}')
    return


def onSignalingStateChange(webrtcDAT: webrtcDAT, connectionId: str, newState: str):
    return


def onIceConnectionStateChange(webrtcDAT: webrtcDAT, connectionId: str, newState: str):
    return


def onIceGatheringStateChange(webrtcDAT: webrtcDAT, connectionId: str, newState: str):
    return
