"""Sends lobe activation to TouchDesigner over OSC.

Modes: live (from the playing track), sweep / pulse / hold (test patterns), off.
`live` stays on even with no music, sending the idle levels.

Contract: /lobes/activation with one float 0-1 per region, in the order of
regions.json. See docs/protocol.md section 1.3.
"""

import asyncio
import json
import logging
import math
import time
from pathlib import Path

from .mapping import smooth

logger = logging.getLogger(__name__)

OSC_ADDRESS = '/lobes/activation'

# Synchrony travels on its own address, not as an eighth argument of
# /lobes/activation: that message becomes a 7-sample table for the Lookup CHOP
# in TD, and one extra argument would shift every neuron onto the wrong lobe.
SYNC_ADDRESS = '/lobes/sync'

SEND_RATE_HZ = 30.0

# How far each send moves toward the target (0-1). At 30 Hz, 0.08 gives roughly
# a half-second transition.
SMOOTHING = 0.08

# Region order is generated by tools/split_lobes.py; reading it from there keeps
# backend and TouchDesigner from drifting apart silently.
REGIONS_JSON = (Path(__file__).resolve().parents[2]
                / 'touchdesigner' / 'exports' / 'regions' / 'regions.json')

FALLBACK_REGIONS = ['frontal', 'parietal', 'temporal', 'occipital',
                    'cerebellum', 'brainstem', 'other_midline']


def load_regions() -> list[str]:
    """Region names in lobe_id order."""
    try:
        data = json.loads(REGIONS_JSON.read_text())
        regions = [r['region'] for r in sorted(data['regions'],
                                               key=lambda r: r['lobe_id'])]
        if regions:
            return regions
        logger.warning('%s non contiene regioni, uso il fallback', REGIONS_JSON)
    except FileNotFoundError:
        logger.warning('%s non trovato: rigenera con tools/split_lobes.py. '
                       'Uso l\'ordine di default.', REGIONS_JSON)
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        logger.warning('%s illeggibile (%s), uso il fallback', REGIONS_JSON, exc)
    return list(FALLBACK_REGIONS)


class LobeSender:
    """Background task sending activation to TD at a constant rate."""

    MODES = ('live', 'sweep', 'pulse', 'hold', 'off')

    def __init__(self, osc, regions: list[str], rate_hz: float = SEND_RATE_HZ):
        self.osc = osc
        self.regions = regions
        self.rate_hz = rate_hz
        self.mode = 'off'
        self._task: asyncio.Task | None = None
        self._started_at = 0.0
        #: returns the current activation; set by main.py
        self.provider = None
        #: returns the current synchrony (0-1)
        self.sync_provider = None
        self._current: list[float] | None = None
        self._sync = 0.0
        self._hold: list[float] | None = None

    @property
    def running(self) -> bool:
        return self._task is not None and not self._task.done()

    def _pattern(self, elapsed: float) -> list[float]:
        n = len(self.regions)

        if self.mode == 'live':
            target = self.provider() if self.provider else None
            if target is None or len(target) != n:
                target = [0.0] * n
            # Section boundaries are sharp discontinuities: without smoothing
            # the whole brain would jump from one frame to the next.
            self._current = smooth(self._current, target, SMOOTHING)
            return self._current

        if self.mode == 'hold':
            return self._hold or [0.0] * n

        if self.mode == 'pulse':
            value = (math.sin(elapsed * math.pi) + 1) / 2
            return [value] * n

        if self.mode == 'sweep':
            # A bump travelling across the regions and wrapping around. Width > 1
            # overlaps neighbouring lobes so transitions are not abrupt.
            period = 6.0
            width = 1.4
            head = (elapsed / period * n) % n
            values = []
            for i in range(n):
                raw = abs(i - head)
                distance = min(raw, n - raw)  # cyclic: last wraps to first
                values.append(max(0.0, 1.0 - distance / width))
            return values

        return [0.0] * n

    def _sync_value(self) -> float:
        """Synchrony to send right now. Test modes use 1: a unison flash is
        easier to read than scattered firing when checking the chain."""
        if self.mode != 'live':
            return 1.0
        target = self.sync_provider() if self.sync_provider else 0.0
        self._sync += (float(target) - self._sync) * SMOOTHING
        return round(self._sync, 4)

    async def _loop(self):
        interval = 1.0 / self.rate_hz
        try:
            while True:
                self.osc.send(OSC_ADDRESS, *self._pattern(time.monotonic() - self._started_at))
                self.osc.send(SYNC_ADDRESS, self._sync_value())
                await asyncio.sleep(interval)
        except asyncio.CancelledError:
            raise

    def start(self, mode: str) -> None:
        if mode not in self.MODES:
            raise ValueError(f'modo sconosciuto: {mode!r} (attesi: {self.MODES})')

        self.stop()
        self.mode = mode
        self._current = None

        if mode == 'off':
            # One last zero send: otherwise TD keeps the last value received and
            # the lobes freeze lit.
            self.osc.send(OSC_ADDRESS, *([0.0] * len(self.regions)))
            self.osc.send(SYNC_ADDRESS, 0.0)
            self._sync = 0.0
            logger.info('Invio attivazione lobi fermato')
            return

        self._started_at = time.monotonic()
        self._task = asyncio.create_task(self._loop())
        logger.info('Invio attivazione lobi avviato: modo=%s, %d regioni, %.0f Hz',
                    mode, len(self.regions), self.rate_hz)

    def hold_region(self, region: str) -> None:
        """Light one region and leave it lit, to check where it appears."""
        if region not in self.regions:
            raise ValueError(f'regione sconosciuta: {region!r} (attese: {self.regions})')
        self._hold = [1.0 if name == region else 0.0 for name in self.regions]
        self.start('hold')

    def stop(self) -> None:
        if self._task is not None:
            self._task.cancel()
            self._task = None
        self.mode = 'off'

    def state(self) -> dict:
        return {
            'running': self.running,
            'mode': self.mode,
            'rate_hz': self.rate_hz,
            'address': OSC_ADDRESS,
            'sync_address': SYNC_ADDRESS,
            'sync': round(self._sync, 3),
            'regions': self.regions,
        }
